SMAdapter Class Reference
Smart Meter Adapter.
#include <SMAdapter.h>
Public Member Functions
SMAdapter (long int i)
SMAdapter (long int i, smart3p::Unit *u)
~SMAdapter ()
void registerInfoFromUC (omnetpp::cMessage *msg)
cInteger * getId ()
cInteger * getAnonId ()
omnetpp::cQueue * startSessionKeyExchange (omnetpp::cMessage *msg)
bool endOfSessionKeyExchange (omnetpp::cMessage *msg)
omnetpp::cMessage * sendEnergyConsumption (omnetpp::cMessage *msg)
void log (char *, double)
void addSimTime (double)
Additional Inherited Members
Detailed Description
Smart Meter Adapter.
Definition at line 15 of file SMAdapter.h.
Constructor & Destructor Documentation
SMAdapter() [1/2]
SMAdapter::SMAdapter (long int i)
Parameters
i Smart Meter ID
Definition at line 16 of file SMAdapter.cc.
SMAdapter() [2/2]
SMAdapter::SMAdapter (long int i, smart3p::Unit * u)
Parameters
i Smart Meter ID
u Output unit class (used for debugging)
See also
log(char*, double), addSimTime(double)
Definition at line 21 of file SMAdapter.cc.
 SMAdapter()
SMAdapter::~SMAdapter ()
Definition at line 26 of file SMAdapter.cc.
Member Function Documentation
addSimTime()
void SMAdapter::addSimTime (double time)
Adds time to the simulation
Definition at line 31 of file SMAdapter.cc.
References Adapter::out.
endOfSessionKeyExchange()
bool SMAdapter::endOfSessionKeyExchange (omnetpp::cMessage * msg)
Finishes the session key exchange phase.
Returns
tells if the final session key passed verification.
Definition at line 155 of file SMAdapter.cc.
References SMImp::SmartMeter::recieveHMAC().
getAnonId()
cInteger * SMAdapter::getAnonId ()
Gets the Anonymous ID from the underlying protocol Smart Meter
Definition at line 42 of file SMAdapter.cc.
References SMImp::SmartMeter::getAnonId().
getId()
cInteger * SMAdapter::getId ()
Gets the ID from the underlying protocol Smart Meter
Definition at line 47 of file SMAdapter.cc.
References SMImp::Requester::getId().
log()
void SMAdapter::log (char * tag, double value)
Emits statistical data.
Definition at line 36 of file SMAdapter.cc.
References Adapter::out.
registerInfoFromUC()
void SMAdapter::registerInfoFromUC (omnetpp::cMessage * msg)
Registers key data from Utility Company.
Definition at line 52 of file SMAdapter.cc.
References SMImp::MasterKey::g, SMImp::SmartMeter::generateKeys(), SMImp::MasterKey::p, SMImp::Payload::params, Adapter::print(), SMImp::Payload::priv, SMImp::Payload::pub, SMImp::MasterKey::q, SMImp::SmartMeter::setAnonId(), SMImp::SmartMeter::setHMACKey(), Adapter::verbose, and SMImp::MasterKey::x.
sendEnergyConsumption()
omnetpp::cMessage * SMAdapter::sendEnergyConsumption (omnetpp::cMessage * msg)
Sends encrypted energy use data to Trusted Thrid Party.
Definition at line 166 of file SMAdapter.cc.
References SMImp::HMACPayload::c1, SMImp::HMACPayload::c2, smart3p::SMPacket::getValue(), SMImp::HMACPayload::hmac, SMImp::HMACPayload::id, SMImp::HMACPayload::messageLength, SMImp::Packet::pl, Adapter::print(), SMImp::SmartMeter::sendDataToTTP(), SMImp::HMACPayload::timeStamp, and Adapter::verbose.
startSessionKeyExchange()
omnetpp::cQueue * SMAdapter::startSessionKeyExchange (omnetpp::cMessage * msg)
Starts the session key generation.
Returns
Queue of packets to be sent to Trusted Thrid Party.
Definition at line 82 of file SMAdapter.cc.
References SMImp::HMACPayload::c1, SMImp::HMACPayload::c2, smart3p::SMPacket::getId(), SMImp::Requester::getId(), SMImp::Requester::getPublicMu(), SMImp::Requester::getPublicPartial(), SMImp::HMACPayload::hmac, SMImp::HMACPayload::messageLength, SMImp::Packet::pl, Adapter::print(), SMImp::HMACPayload::r, SMImp::SmartMeter::sessionKeyExchange(), smart3p::SMPacket::setId(), and SMImp::HMACPayload::timeStamp.
The documentation for this class was generated from the following files:
src/SMAdapter.h
src/SMAdapter.cc