smart3p::TrustedThirdParty Class Reference
Trusted Thrid Party for the simulation.
#include <TrustedThirdParty.h>
Public Member Functions
void print (char *)
Print debug messages.
Protected Member Functions
virtual void initialize ()
virtual void timedHandleMessage (cMessage *msg)
Default message handler.
Additional Inherited Members
Detailed Description
Trusted Thrid Party for the simulation.
Definition at line 28 of file TrustedThirdParty.h.
Member Function Documentation
initialize()
void smart3p::TrustedThirdParty::initialize () [protected], [virtual]
Definition at line 29 of file TrustedThirdParty.cc.
print()
void smart3p::TrustedThirdParty::print (char *)
Print debug messages.
timedHandleMessage()
void smart3p::TrustedThirdParty::timedHandleMessage (cMessage * msg) [protected], [virtual]
Default message handler.
Reimplemented from smart3p::Unit.
Definition at line 39 of file TrustedThirdParty.cc.
References TTPAdapter::finishSessionKeyExchange(), TTPAdapter::processDataFromSM(), TTPAdapter::registerAtUC(), TTPAdapter::registerInfoFromUC(), TTPAdapter::registerSM(), and TTPAdapter::startSessionKeyExchange().
The documentation for this class was generated from the following files:
src/TrustedThirdParty.h
src/TrustedThirdParty.cc