smart3p::SMPacket Class Reference
#include <SMPacket_m.h>
Public Member Functions
SMPacket (const char *name=nullptr, int kind=0)
SMPacket (const SMPacket &other)
virtual ~SMPacket ()
SMPacket & operator= (const SMPacket &other)
virtual SMPacket * dup () const
virtual void parsimPack (omnetpp::cCommBuffer *b) const
virtual void parsimUnpack (omnetpp::cCommBuffer *b)
virtual int getId () const
virtual void setId (int id)
virtual double getValue () const
virtual void setValue (double value)
virtual int getSmGateID () const
virtual void setSmGateID (int smGateID)
virtual int getCollGateID () const
virtual void setCollGateID (int collGateID)
virtual const char * getExtraInfo () const
virtual void setExtraInfo (const char *extraInfo)
virtual const char * getExtraInfoSize () const
virtual void setExtraInfoSize (const char *extraInfoSize)
Protected Member Functions
bool operator== (const SMPacket &)
Protected Attributes
int id
double value
int smGateID
int collGateID
::omnetpp::opp_string extraInfo
::omnetpp::opp_string extraInfoSize
Detailed Description
Class generated from SMPacket.msg:6 by nedtool.
   //
   // Smart Meter Packet
   //
   packet SMPacket
   {
       int id;
       double value;
       int smGateID;
       int collGateID;
       string extraInfo;
       string extraInfoSize;
   }
 o
Definition at line 36 of file SMPacket_m.h.
Constructor & Destructor Documentation
SMPacket() [1/2]
smart3p::SMPacket::SMPacket (const char * name = nullptr, int kind = 0)
Definition at line 167 of file SMPacket_m.cc.
References collGateID, smGateID, and value.
SMPacket() [2/2]
smart3p::SMPacket::SMPacket (const SMPacket & other)
Definition at line 175 of file SMPacket_m.cc.
 SMPacket()
smart3p::SMPacket::~SMPacket () [virtual]
Definition at line 180 of file SMPacket_m.cc.
Member Function Documentation
dup()
virtual SMPacket* smart3p::SMPacket::dup () const [inline], [virtual]
Definition at line 58 of file SMPacket_m.h.
References getCollGateID(), getExtraInfo(), getExtraInfoSize(), getId(), getSmGateID(), getValue(), parsimPack(), parsimUnpack(), setCollGateID(), setExtraInfo(), setExtraInfoSize(), setId(), setSmGateID(), setValue(), and SMPacket().
getCollGateID()
int smart3p::SMPacket::getCollGateID () const [virtual]
Definition at line 254 of file SMPacket_m.cc.
References collGateID.
getExtraInfo()
const char * smart3p::SMPacket::getExtraInfo () const [virtual]
Definition at line 264 of file SMPacket_m.cc.
References extraInfo.
getExtraInfoSize()
const char * smart3p::SMPacket::getExtraInfoSize () const [virtual]
Definition at line 274 of file SMPacket_m.cc.
References extraInfoSize.
getId()
int smart3p::SMPacket::getId () const [virtual]
Definition at line 224 of file SMPacket_m.cc.
References id.
getSmGateID()
int smart3p::SMPacket::getSmGateID () const [virtual]
Definition at line 244 of file SMPacket_m.cc.
References smGateID.
getValue()
double smart3p::SMPacket::getValue () const [virtual]
Definition at line 234 of file SMPacket_m.cc.
References value.
operator=()
SMPacket & smart3p::SMPacket::operator= (const SMPacket & other)
Definition at line 184 of file SMPacket_m.cc.
References collGateID, extraInfo, extraInfoSize, id, smGateID, and value.
operator==()
bool smart3p::SMPacket::operator== (const SMPacket &) [protected]
parsimPack()
void smart3p::SMPacket::parsimPack (omnetpp::cCommBuffer * b) const [virtual]
Definition at line 202 of file SMPacket_m.cc.
References collGateID, smart3p::doParsimPacking(), extraInfo, extraInfoSize, smGateID, and value.
parsimUnpack()
void smart3p::SMPacket::parsimUnpack (omnetpp::cCommBuffer * b) [virtual]
Definition at line 213 of file SMPacket_m.cc.
References collGateID, smart3p::doParsimUnpacking(), extraInfo, extraInfoSize, smGateID, and value.
setCollGateID()
void smart3p::SMPacket::setCollGateID (int collGateID) [virtual]
Definition at line 259 of file SMPacket_m.cc.
References collGateID.
setExtraInfo()
void smart3p::SMPacket::setExtraInfo (const char * extraInfo) [virtual]
Definition at line 269 of file SMPacket_m.cc.
References extraInfo.
setExtraInfoSize()
void smart3p::SMPacket::setExtraInfoSize (const char * extraInfoSize) [virtual]
Definition at line 279 of file SMPacket_m.cc.
References extraInfoSize.
setId()
void smart3p::SMPacket::setId (int id) [virtual]
Definition at line 229 of file SMPacket_m.cc.
References id.
setSmGateID()
void smart3p::SMPacket::setSmGateID (int smGateID) [virtual]
Definition at line 249 of file SMPacket_m.cc.
References smGateID.
setValue()
void smart3p::SMPacket::setValue (double value) [virtual]
Definition at line 239 of file SMPacket_m.cc.
References value.
Field Documentation
collGateID
int smart3p::SMPacket::collGateID [protected]
Definition at line 42 of file SMPacket_m.h.
extraInfo
::omnetpp::opp_string smart3p::SMPacket::extraInfo [protected]
Definition at line 43 of file SMPacket_m.h.
extraInfoSize
::omnetpp::opp_string smart3p::SMPacket::extraInfoSize [protected]
Definition at line 44 of file SMPacket_m.h.
id
int smart3p::SMPacket::id [protected]
Definition at line 39 of file SMPacket_m.h.
smGateID
int smart3p::SMPacket::smGateID [protected]
Definition at line 41 of file SMPacket_m.h.
value
double smart3p::SMPacket::value [protected]
Definition at line 40 of file SMPacket_m.h.
The documentation for this class was generated from the following files:
src/SMPacket_m.h
src/SMPacket_m.cc