UCAdapter Class Reference
Utility Company Adapter.
#include <UCAdapter.h>
Public Member Functions
UCAdapter (smart3p::Unit *u)
UCAdapter ()
~UCAdapter ()
omnetpp::cMessage * registerSM (omnetpp::cMessage *)
omnetpp::cMessage * registerTTP (omnetpp::cMessage *msg)
void finishRegisteringTTP (omnetpp::cMessage *msg)
omnetpp::cMessage * sessionKeyStartFromTTP (omnetpp::cMessage *msg)
bool sessionKeyExchangeFromTTP (omnetpp::cMessage *msg)
bool sessionKeyExchangeFromSM (omnetpp::cMessage *msg)
bool energyConsumptionProcessing (omnetpp::cMessage *msg)
Additional Inherited Members
Detailed Description
Utility Company Adapter.
Definition at line 15 of file UCAdapter.h.
Constructor & Destructor Documentation
UCAdapter() [1/2]
UCAdapter::UCAdapter (smart3p::Unit * u)
Parameters
u Output unit class (used for debugging)
Definition at line 9 of file UCAdapter.cc.
UCAdapter() [2/2]
UCAdapter::UCAdapter ()
Definition at line 14 of file UCAdapter.cc.
 UCAdapter()
UCAdapter::~UCAdapter ()
Definition at line 19 of file UCAdapter.cc.
Member Function Documentation
energyConsumptionProcessing()
bool UCAdapter::energyConsumptionProcessing (omnetpp::cMessage * msg)
Passes energy consuption data packets to lower-level protocol implementation for HMAC verification.
Returns
Indicates if verification failed or not (false if failed).
Definition at line 157 of file UCAdapter.cc.
References sessionKeyExchangeFromSM().
finishRegisteringTTP()
void UCAdapter::finishRegisteringTTP (omnetpp::cMessage * msg)
Finalizes Trusted Third Party registration.
registerSM()
omnetpp::cMessage * UCAdapter::registerSM (omnetpp::cMessage * msg)
Registers Smart Meter with Utility Company.
Definition at line 24 of file UCAdapter.cc.
References SMImp::UtilityCompany::addSMData(), SMImp::UtilityCompany::generatePartialKeys(), List< T >::get(), smart3p::SMPacket::getId(), SMImp::UtilityCompany::getSM(), smart3p::SMPacket::getSmGateID(), SMImp::UtilityCompany::registerSM(), and smart3p::SMPacket::setSmGateID().
registerTTP()
omnetpp::cMessage * UCAdapter::registerTTP (omnetpp::cMessage * msg)
Registers Trusted Third Party with Utility Company.
Definition at line 62 of file UCAdapter.cc.
References SMImp::MasterKey::g, SMImp::UtilityCompany::generatePartialKeys(), smart3p::SMPacket::getId(), SMImp::MasterKey::p, SMImp::Payload::params, SMImp::Payload::priv, SMImp::Payload::pub, SMImp::MasterKey::q, SMImp::UtilityCompany::registerTTP(), and SMImp::MasterKey::x.
sessionKeyExchangeFromSM()
bool UCAdapter::sessionKeyExchangeFromSM (omnetpp::cMessage * msg)
Passes session key exchange data from Smart Meter to lower-level protocol implementation.
Definition at line 133 of file UCAdapter.cc.
References List< T >::get(), SMImp::UtilityCompany::getSM(), SMImp::HMACPayload::id, and SMImp::UtilityCompany::verifyHMAC().
sessionKeyExchangeFromTTP()
bool UCAdapter::sessionKeyExchangeFromTTP (omnetpp::cMessage * msg)
Passes session key exchange data from Trusted Thrid Party to lower-level protocol implementation.
Definition at line 107 of file UCAdapter.cc.
References List< T >::get(), SMImp::UtilityCompany::getSMbyAnonId(), SMImp::HMACPayload::id, smart3p::SMPacket::setCollGateID(), smart3p::SMPacket::setSmGateID(), and SMImp::UtilityCompany::verifyHMAC().
sessionKeyStartFromTTP()
omnetpp::cMessage * UCAdapter::sessionKeyStartFromTTP (omnetpp::cMessage * msg)
Passes session key start signal to the lower-level protocol implementation.
Definition at line 91 of file UCAdapter.cc.
References List< T >::get(), SMImp::UtilityCompany::getSMbyAnonId(), smart3p::SMPacket::setCollGateID(), and smart3p::SMPacket::setSmGateID().
The documentation for this class was generated from the following files:
src/UCAdapter.h
src/UCAdapter.cc