smart3p::DataGenerator Class Reference
Generates data for smart3p::SmartMeter.
#include <DataGenerator.h>
Protected Member Functions
virtual void initialize ()
Class initilization.
virtual void handleMessage (cMessage *msg)
Main message handler.
virtual void finish ()
Called when simulation is shut down.
Detailed Description
Generates data for smart3p::SmartMeter.
Definition at line 14 of file DataGenerator.h.
Member Function Documentation
finish()
void smart3p::DataGenerator::finish () [protected], [virtual]
Called when simulation is shut down.
Definition at line 214 of file DataGenerator.cc.
handleMessage()
void smart3p::DataGenerator::handleMessage (cMessage * msg) [protected], [virtual]
Main message handler.
Definition at line 151 of file DataGenerator.cc.
References smart3p::SMPacket::getId(), and smart3p::SMPacket::setId().
initialize()
void smart3p::DataGenerator::initialize () [protected], [virtual]
Class initilization.
Definition at line 15 of file DataGenerator.cc.
References smart3p::SMPacket::setValue().
The documentation for this class was generated from the following files:
src/DataGenerator.h
src/DataGenerator.cc