SMImp::SmartMeter Class Reference
Smart Meter protocol implementation.
#include <SmartMeter.h>
Public Member Functions
SmartMeter (Integer, CryptoPP::SHA1 *)
SmartMeter (Integer, ::SMAdapter *)
SmartMeter (Integer)
virtual ~SmartMeter ()
void setHMACKey (Integer)
bool generateKeys (Payload)
void setAnonId (Integer)
Integer getAnonId ()
Packet * sendDataToTTP (Integer data)
Packet * sessionKeyExchange (char *m, Integer l, Integer trustedPartyId, Integer trustedPartyKey, Integer trustedPartyMu)
bool recieveHMAC (Integer c1, Integer c2, Integer ttpId)
Additional Inherited Members
Detailed Description
Smart Meter protocol implementation.
Most variables have been named after their respective names given in the original research paper available here. See section 5 (Page 7) for the beginning of the protocol implementation.
Definition at line 15 of file SmartMeter.h.
Constructor & Destructor Documentation
SmartMeter() [1/3]
SMImp::SmartMeter::SmartMeter (Integer , CryptoPP::SHA1 *)
See also
SMImp::Requester::Requester(Integer,SHA1)
SmartMeter() [2/3]
SMImp::SmartMeter::SmartMeter (Integer , ::SMAdapter *)
For debugging.
SmartMeter() [3/3]
SMImp::SmartMeter::SmartMeter (Integer i)
Definition at line 34 of file SmartMeter.cc.
References SMImp::Requester::Requester(), and SmartMeter().
 SmartMeter()
SMImp::SmartMeter::~SmartMeter () [virtual]
Definition at line 49 of file SmartMeter.cc.
Member Function Documentation
generateKeys()
bool SMImp::SmartMeter::generateKeys (Payload pl)
Generates keys from payload given by Utility Company.
Definition at line 11 of file SmartMeter.cc.
References SMImp::MasterKey::g, SMImp::Requester::getPartials(), SMImp::Requester::keys, SMImp::MasterKey::p, SMImp::Requester::params, SMImp::Key::piece, SMImp::KeyPair::priv, SMImp::KeyPair::pub, SMImp::MasterKey::q, and SMImp::Requester::rng.
getAnonId()
Integer SMImp::SmartMeter::getAnonId ()
See also
SMImp::Requester::getAnonId()
Definition at line 53 of file SmartMeter.cc.
recieveHMAC()
bool SMImp::SmartMeter::recieveHMAC (Integer c1, Integer c2, Integer ttpId)
Used at the end of the session key exchange phase. HMAC verifies, then decrypts the final shared session key.
Parameters
c1 Part 1 of the encrypted session key.
c2 Part 2 of the encrypted session key.
ttpId ID of the Trusted Third Party.
Definition at line 221 of file SmartMeter.cc.
References SMAdapter::addSimTime(), SMImp::MasterKey::g, SMImp::Requester::keys, SMAdapter::log(), SMImp::MasterKey::p, SMImp::Requester::params, SMImp::Key::partial, SMImp::Key::piece, and SMImp::KeyPair::priv.
sendDataToTTP()
Packet * SMImp::SmartMeter::sendDataToTTP (Integer data)
Encrypts data to be sent to the Trusted Thrid Party.
Parameters
data Data to be encrypted and sent to Trusted Thrid Party.
Returns
Packet of encrypted data.
Definition at line 69 of file SmartMeter.cc.
References SMAdapter::addSimTime(), SMImp::HMACPayload::c1, SMImp::HMACPayload::c2, DEBUG, SMImp::MasterKey::g, SMImp::HMACPayload::hmac, SMImp::Requester::id, SMImp::HMACPayload::id, SMAdapter::log(), SMImp::HMACPayload::messageLength, SMImp::MasterKey::p, SMImp::Requester::params, SMImp::Packet::pl, SMImp::Requester::R, SMImp::HMACPayload::r, SMImp::Requester::shaone, SMImp::HMACPayload::timeStamp, and SMImp::MasterKey::x.
sessionKeyExchange()
Packet * SMImp::SmartMeter::sessionKeyExchange (char * m, Integer l, Integer trustedPartyId, Integer trustedPartyKey, Integer trustedPartyMu)
Performs all the processes to both generate and split up the session key, returning an array of packets to encasulate in the Adapter.
Parameters
m Message, or the session key to be generated, see SMAdaoter::startSessionKeyExchange(omnetpp::cMessage* msg).
l Length of the session key, does not need to be a multiple of 4 since char('0')s (or int(48)) are padded to reach the desired length.
trustedPartyId ID of the Trusted Third Party to share a session key with.
trustedPartyKey Missnamed variable, this is just the first piece of the public key - specificially the component generated by the Utility Company.
trustedPartyMu second peice of the public key, generated by the Trusted Third Party.
Returns
Returns array of messages to be encapsulated and sent to Trusted Third Party. Array is of length (l+(4-(l%4)))/4, or ceiling(l/4) where l is the length of the session key.
Definition at line 130 of file SmartMeter.cc.
References SMAdapter::addSimTime(), SMImp::HMACPayload::c1, SMImp::HMACPayload::c2, SMImp::Packet::dest, SMImp::MasterKey::g, SMImp::HMACPayload::hmac, SMImp::Requester::id, SMImp::HMACPayload::id, SMAdapter::log(), SMImp::HMACPayload::messageLength, SMImp::MasterKey::p, SMImp::Requester::params, SMImp::Packet::pl, SMImp::Requester::R, SMImp::HMACPayload::r, SMImp::Requester::rng, SMImp::Requester::shaone, SMImp::HMACPayload::timeStamp, and SMImp::MasterKey::x.
setAnonId()
void SMImp::SmartMeter::setAnonId (Integer a)
Sets the anonymous ID
Definition at line 58 of file SmartMeter.cc.
setHMACKey()
void SMImp::SmartMeter::setHMACKey (Integer i)
Sets HMAC to be used for verification.
Definition at line 63 of file SmartMeter.cc.
The documentation for this class was generated from the following files:
src/crypto/SmartMeter.h
src/crypto/SmartMeter.cc