smart3p::SmartMeter Class Reference
Simulation Smart Meter class.
#include <SmartMeter.h>
Public Member Functions
void log (simsignal_t id, double value)
void log (char *tag, double value)
void addSimTime (double t)
Protected Member Functions
virtual void initialize ()
Initilizer.
virtual void timedHandleMessage (cMessage *msg)
Message Handler.
virtual void finish ()
Deconstructor.
Additional Inherited Members
Detailed Description
Simulation Smart Meter class.
Definition at line 15 of file SmartMeter.h.
Member Function Documentation
addSimTime()
void smart3p::SmartMeter::addSimTime (double t)
Adds additional time to the simulation based upon the amount of time taken to perform protocol-level processing.
Omnet++ treats all computations as taking no time at all in the simulation. So to properly record statistical data we have to add additional time to the simulation.
Parameters
t Time to add to the simulation.
Definition at line 34 of file SmartMeter.cc.
finish()
void smart3p::SmartMeter::finish () [protected], [virtual]
Deconstructor.
Definition at line 192 of file SmartMeter.cc.
References SMAdapter::endOfSessionKeyExchange(), smart3p::SMPacket::getId(), SMAdapter::registerInfoFromUC(), SMAdapter::sendEnergyConsumption(), smart3p::SMPacket::setExtraInfo(), smart3p::SMPacket::setId(), SMAdapter::startSessionKeyExchange(), and smart3p::Unit::timeoutEvent.
initialize()
void smart3p::SmartMeter::initialize () [protected], [virtual]
Initilizer.
Definition at line 16 of file SmartMeter.cc.
log() [1/2]
void smart3p::SmartMeter::log (simsignal_t id, double value)
Emits statistical data to be registered by the simulation.
Parameters
id simsignal_t id of the data collection to put value into.
value The value to add to the data collection identified by id.
See also
log(char* tag, double value)
Definition at line 46 of file SmartMeter.cc.
log() [2/2]
void smart3p::SmartMeter::log (char * tag, double value)
Emits statistical data to be registered by the simulation.
Parameters
tag The c-string which corresponds to the id of the data collection to add data to.
value The value to add to the data collection identified by tag.
See also
log(simsignal_t id, double value)
Definition at line 51 of file SmartMeter.cc.
References log(), smart3p::Unit::timeoutEvent, and smart3p::Unit::waitForDelivery.
timedHandleMessage()
void smart3p::SmartMeter::timedHandleMessage (cMessage * msg) [protected], [virtual]
Message Handler.
Reimplemented from smart3p::Unit.
Definition at line 108 of file SmartMeter.cc.
References smart3p::Unit::timeoutEvent.
The documentation for this class was generated from the following files:
src/SmartMeter.h
src/SmartMeter.cc