SMImp::TrustedParty Class Reference
Trusted Third Party protocol implementation.
#include <TrustedParty.h>
Public Member Functions
TrustedParty (Integer)
TrustedParty (Integer, TTPAdapter *)
virtual ~TrustedParty ()
char * getMessage ()
void registerSM (int)
void addDataToSM (int id, Integer *data)
List< Integer > * getSM (int id)
List< Integer > * getRandomSM ()
Iterator< List< Integer > > * getSMIterator ()
Packet confirmSession (Integer req, Integer smId, Key smKey)
bool recieveHMAC (Integer length, Integer c1, Integer c2, Integer smId, Key smKey, Integer r)
Integer recieveData (Integer length, Integer c1, Integer c2, Integer smId, Integer timeStamp)
Additional Inherited Members
Detailed Description
Trusted Third Party protocol implementation.
Most variables have been named after their respective names given in the original research paper available here. See section 5 (Page 7) for the beginning of the protocol implementation.
Definition at line 15 of file TrustedParty.h.
Constructor & Destructor Documentation
TrustedParty() [1/2]
SMImp::TrustedParty::TrustedParty (Integer i)
Definition at line 16 of file TrustedParty.cc.
TrustedParty() [2/2]
SMImp::TrustedParty::TrustedParty (Integer i, TTPAdapter * o)
For debugging.
Definition at line 9 of file TrustedParty.cc.
 TrustedParty()
SMImp::TrustedParty::~TrustedParty () [virtual]
Definition at line 23 of file TrustedParty.cc.
Member Function Documentation
addDataToSM()
void SMImp::TrustedParty::addDataToSM (int id, Integer * data)
Adds arbitrary data to the local Smart Meter representation identified by id.
Parameters
id ID of the Smart Meter to add data to.
data Data to add to the local Smart Meter representation.
Definition at line 49 of file TrustedParty.cc.
References List< T >::add(), List< T >::get(), and List< T >::size().
confirmSession()
Packet SMImp::TrustedParty::confirmSession (Integer req, Integer smId, Key smKey)
Recieves session key exchange data from Smart Meter.
Parameters
req Shared secret R for use with future encryption.
smId ID (anonymous) for identifying the Smart Meter (used by getSM(int id)).
smKey Public key of the Smart Meter.
Returns
Packet to be sent back to the Smart Meter.
Definition at line 70 of file TrustedParty.cc.
References List< T >::add(), SMImp::HMACPayload::c1, SMImp::HMACPayload::c2, SMImp::Packet::dest, SMImp::MasterKey::g, List< T >::get(), SMImp::HMACPayload::hmac, SMImp::Requester::id, SMImp::HMACPayload::id, SMImp::MasterKey::p, SMImp::Requester::params, SMImp::Key::partial, SMImp::Key::piece, SMImp::Packet::pl, SMImp::Requester::rng, SMImp::Requester::shaone, SMImp::HMACPayload::timeStamp, and SMImp::MasterKey::x.
getMessage()
char* SMImp::TrustedParty::getMessage ()
Helper function for the Adapter to queuery the current message.
Returns
message
See also
message.
getRandomSM()
List< Integer > * SMImp::TrustedParty::getRandomSM ()
Gets a random Smart Meter representation for use with session key exchange.
Returns
Local Smart Meter representation of arbitrary data.
Definition at line 60 of file TrustedParty.cc.
References List< T >::getRandom().
getSM()
List< Integer > * SMImp::TrustedParty::getSM (int id)
Gets local Smart Meter representation by ID
Parameters
id Smart Meter ID to retrieve.
Returns
Local Smart Meter representation of arbitrary data.
Definition at line 55 of file TrustedParty.cc.
References List< T >::get().
getSMIterator()
Iterator< List< Integer > > * SMImp::TrustedParty::getSMIterator ()
Get an iterator to iterate over all available Smart Meters.
Returns
Iterator to iterate with.
Definition at line 65 of file TrustedParty.cc.
References List< T >::iterator().
recieveData()
Integer SMImp::TrustedParty::recieveData (Integer length, Integer c1, Integer c2, Integer smId, Integer timeStamp)
Recieve, verify and decrypt energy usage data.
Parameters
length Length of the message (unused as it is equivalent to the sum of the lengths of c1 and c2)
c1 Part 1 of the encrypted energy usage data.
c2 Part 2 of the encrypted energy usage data.
smId ID (anonymous) of the Smart Meter the data originated from.
timeStamp Timestamp of the data.
Returns
-1 if failed to verify. Any other value is the byte-encoded string of the data, see TTPAdapter::processDataFromSM(omnetpp::cMessage* msg)
Definition at line 131 of file TrustedParty.cc.
References DEBUG, SMImp::MasterKey::g, List< T >::get(), SMImp::MasterKey::p, SMImp::Requester::params, and SMImp::Requester::sessionKey.
recieveHMAC()
bool SMImp::TrustedParty::recieveHMAC (Integer length, Integer c1, Integer c2, Integer smId, Key smKey, Integer r)
Finishes the Session Key exchange phase for the Trusted Third Party.
Parameters
length Total length of the session key. Unlike recieveHMAC(Integer length, Integer c1, Integer c2, Integer id, Key smKey, Integer r) the sum of the lengths of c1 and c2 may be less than the length of the entire session key.
c1 Part 1 of the encrypted Session Key.
c2 Part 2 of the encrypted Session Key.
smId ID (anonymous) of the Smart Meter the Session Key originated from.
smKey Public key of Smart Meter.
r shared-secret used for message verification.
Returns
Returns true if session key passed verification, false otherwise.
Definition at line 180 of file TrustedParty.cc.
References List< T >::add(), DEBUG, SMImp::MasterKey::g, List< T >::get(), SMImp::Requester::keys, SMImp::MasterKey::p, SMImp::Requester::params, SMImp::Key::partial, SMImp::Key::piece, SMImp::KeyPair::priv, and SMImp::Requester::sessionKey.
registerSM()
void SMImp::TrustedParty::registerSM (int id)
Adds Smart Meter's id to the SMList.
Definition at line 35 of file TrustedParty.cc.
References List< T >::add().
The documentation for this class was generated from the following files:
src/crypto/TrustedParty.h
src/crypto/TrustedParty.cc