SMImp::UtilityCompany Class Reference
Utility Company protocol-level implementation.
#include <UtilityCompany.h>
Public Member Functions
UtilityCompany (SHA1 *)
UtilityCompany ()
~UtilityCompany ()
bool generateKey (Integer q, const Integer &max, const Integer &equiv, const Integer &mod)
Payload generatePartialKeys (Integer id)
bool verifyHMAC (Integer id, HMACPayload payload)
void registerSM (Integer *id)
void registerTTP (Integer *id)
List< Integer > * getSMbyAnonId (Integer id)
List< Integer > * getSM (Integer id)
List< Integer > * getTTP (Integer id)
void addSMData (Integer *id, Integer *data)
void addTTPData (Integer *id, Integer *data)
int getTTPSize (Integer *id)
Detailed Description
Utility Company protocol-level implementation.
Definition at line 12 of file UtilityCompany.h.
Constructor & Destructor Documentation
UtilityCompany() [1/2]
SMImp::UtilityCompany::UtilityCompany (SHA1 *)
UtilityCompany() [2/2]
SMImp::UtilityCompany::UtilityCompany ()
Definition at line 8 of file UtilityCompany.cc.
References generateKey().
 UtilityCompany()
SMImp::UtilityCompany::~UtilityCompany ()
Definition at line 20 of file UtilityCompany.cc.
References SMImp::MasterKey::g, SMImp::MasterKey::p, SMImp::MasterKey::q, and SMImp::MasterKey::x.
Member Function Documentation
addSMData()
void SMImp::UtilityCompany::addSMData (Integer * id, Integer * data)
Adds arbitrary data to the local Smart Meter representation.
Parameters
id ID of the Smart Meter to add data to.
data Data to add to the local Smart Meter representation.
Definition at line 80 of file UtilityCompany.cc.
References List< T >::add(), List< T >::get(), and List< T >::size().
addTTPData()
void SMImp::UtilityCompany::addTTPData (Integer * id, Integer * data)
Adds arbitrary data to the local Trusted Third Party representation.
Parameters
id ID of the Trusted Third Party to add data to.
data Data to add to the local Trusted Third Party representation.
Definition at line 86 of file UtilityCompany.cc.
References List< T >::add(), List< T >::get(), and List< T >::size().
generateKey()
bool SMImp::UtilityCompany::generateKey (Integer q, const Integer & max, const Integer & equiv, const Integer & mod)
Utilizes CryptoPP's nbtheory to generate paramters for use in key generation.
Heavy comments are utilized in the source file. It is recommended to read through this function in UtilityCompany.cc
Definition at line 152 of file UtilityCompany.cc.
References SMImp::Key::partial, SMImp::KeyPair::priv, and SMImp::KeyPair::pub.
generatePartialKeys()
Payload SMImp::UtilityCompany::generatePartialKeys (Integer id)
Generates partial private and public keys given the ID.
Parameters
id ID of the Requester object to generate a pair of keys for.
Definition at line 194 of file UtilityCompany.cc.
References SMImp::MasterKey::g, SMImp::MasterKey::p, SMImp::Payload::params, SMImp::Key::partial, SMImp::Payload::priv, SMImp::KeyPair::pub, SMImp::Payload::pub, SMImp::MasterKey::q, and SMImp::MasterKey::x.
getSM()
List< Integer > * SMImp::UtilityCompany::getSM (Integer id)
Gets Smart Meter representation by a given ID.
Parameters
id The ID to search for.
Returns
If found, returns the local Smart Meter representation. Returns NULL otherwise.
Definition at line 109 of file UtilityCompany.cc.
References List< T >::get().
getSMbyAnonId()
List< Integer > * SMImp::UtilityCompany::getSMbyAnonId (Integer id)
Gets Smart Meter representation by a given anonymous ID.
Parameters
id The anonymous ID to search for.
Returns
If found, returns the local Smart Meter representation. Returns NULL otherwise.
Definition at line 98 of file UtilityCompany.cc.
References List< T >::get(), Iterator< T >::hasNext(), List< T >::iterator(), and Iterator< T >::next().
getTTP()
List< Integer > * SMImp::UtilityCompany::getTTP (Integer id)
Gets Trusted Third Party representation by a given ID.
Parameters
id The ID to search for.
Returns
If found, returns the local Trusted Third Party representation. Returns NULL otherwise.
Definition at line 114 of file UtilityCompany.cc.
References List< T >::get().
getTTPSize()
int SMImp::UtilityCompany::getTTPSize (Integer * id)
Gets the count of elements in the Trusted Third Party local representation.
Definition at line 92 of file UtilityCompany.cc.
References List< T >::get(), and List< T >::size().
registerSM()
void SMImp::UtilityCompany::registerSM (Integer * id)
Registers Smart Meter with internal list of Smart Meter representations.
Definition at line 55 of file UtilityCompany.cc.
References List< T >::add().
registerTTP()
void SMImp::UtilityCompany::registerTTP (Integer * id)
Registers Trusted Third Party with internal list of Trusted Third Party representations.
Definition at line 68 of file UtilityCompany.cc.
References List< T >::add().
verifyHMAC()
bool SMImp::UtilityCompany::verifyHMAC (Integer id, HMACPayload payload)
Verifies the HMAC of the given payload.
Parameters
id ID of the device to verify the message from.
payload Payload containing the message to be verified.
Definition at line 223 of file UtilityCompany.cc.
References SMImp::HMACPayload::hmac.
The documentation for this class was generated from the following files:
src/crypto/UtilityCompany.h
src/crypto/UtilityCompany.cc