TTPAdapter Class Reference
Trusted Thrid Party Adapter.
#include <TTPAdapter.h>
Public Member Functions
TTPAdapter (int id)
TTPAdapter (int id, smart3p::Unit *u)
~TTPAdapter ()
void registerSM (omnetpp::cMessage *)
omnetpp::cQueue * startSessionKeyExchange ()
omnetpp::cMessage * finishSessionKeyExchange (omnetpp::cMessage *)
void registerInfoFromUC (omnetpp::cMessage *)
omnetpp::cMessage * registerAtUC ()
void processDataFromSM (omnetpp::cMessage *)
Additional Inherited Members
Detailed Description
Trusted Thrid Party Adapter.
Definition at line 11 of file TTPAdapter.h.
Constructor & Destructor Documentation
TTPAdapter() [1/2]
TTPAdapter::TTPAdapter (int id)
Parameters
id Trusted Third Party ID
Definition at line 11 of file TTPAdapter.cc.
TTPAdapter() [2/2]
TTPAdapter::TTPAdapter (int id, smart3p::Unit * u)
Parameters
id Trusted Third Party ID
u Output unit class (used for debugging)
Definition at line 16 of file TTPAdapter.cc.
 TTPAdapter()
TTPAdapter::~TTPAdapter ()
Definition at line 21 of file TTPAdapter.cc.
Member Function Documentation
finishSessionKeyExchange()
omnetpp::cMessage * TTPAdapter::finishSessionKeyExchange (omnetpp::cMessage * msg)
Finishes the session key exchange phase, forwarding the final state to the Smart Meter.
Definition at line 53 of file TTPAdapter.cc.
References SMImp::HMACPayload::c1, SMImp::HMACPayload::c2, SMImp::TrustedParty::confirmSession(), SMImp::Packet::dest, SMImp::HMACPayload::hmac, SMImp::HMACPayload::id, SMImp::Key::partial, SMImp::Key::piece, SMImp::Packet::pl, SMImp::TrustedParty::recieveHMAC(), and SMImp::HMACPayload::timeStamp.
processDataFromSM()
void TTPAdapter::processDataFromSM (omnetpp::cMessage * msg)
Processes energy consumption data from Smart Meter.
Definition at line 130 of file TTPAdapter.cc.
References Adapter::out, Adapter::print(), SMImp::TrustedParty::recieveData(), and Adapter::verbose.
registerAtUC()
omnetpp::cMessage * TTPAdapter::registerAtUC ()
Registers Trusted Thrid Party with Utility Company.
Definition at line 104 of file TTPAdapter.cc.
References SMImp::Requester::getId(), and smart3p::SMPacket::setId().
registerInfoFromUC()
void TTPAdapter::registerInfoFromUC (omnetpp::cMessage * msg)
Registers info recievd from Utility Company regarding key generation.
Definition at line 115 of file TTPAdapter.cc.
References SMImp::Requester::generateKeys(), SMImp::MasterKey::p, and SMImp::Payload::params.
registerSM()
void TTPAdapter::registerSM (omnetpp::cMessage * msg)
Registers Smart Meter with Trusted Thrid Party
Definition at line 98 of file TTPAdapter.cc.
References smart3p::SMPacket::getId(), and SMImp::TrustedParty::registerSM().
startSessionKeyExchange()
omnetpp::cQueue * TTPAdapter::startSessionKeyExchange ()
Begins the session key exchange phase.
Returns
Queue of outgoing packets
Definition at line 26 of file TTPAdapter.cc.
References List< T >::get(), SMImp::Requester::getId(), SMImp::Requester::getPublicMu(), SMImp::Requester::getPublicPartial(), SMImp::TrustedParty::getSMIterator(), Iterator< T >::hasNext(), Iterator< T >::next(), and smart3p::SMPacket::setId().
The documentation for this class was generated from the following files:
src/TTPAdapter.h
src/TTPAdapter.cc