smart3p::UtilityCompany Class Reference
Utility Company class for the simulation.
#include <UtilityCompany.h>
Public Member Functions
UtilityCompany ()
~UtilityCompany ()
Protected Member Functions
virtual void initialize ()
virtual void timedHandleMessage (cMessage *msg)
Default message handler.
Additional Inherited Members
Detailed Description
Utility Company class for the simulation.
Definition at line 31 of file UtilityCompany.h.
Constructor & Destructor Documentation
UtilityCompany()
smart3p::UtilityCompany::UtilityCompany ()
Definition at line 14 of file UtilityCompany.cc.
 UtilityCompany()
smart3p::UtilityCompany::~UtilityCompany ()
Definition at line 21 of file UtilityCompany.cc.
Member Function Documentation
initialize()
void smart3p::UtilityCompany::initialize () [protected], [virtual]
Definition at line 26 of file UtilityCompany.cc.
References smart3p::MeterData::anonymID, smart3p::MeterData::collGate, smart3p::SMPacket::getCollGateID(), smart3p::SMPacket::getExtraInfo(), smart3p::SMPacket::getId(), smart3p::SMPacket::getSmGateID(), smart3p::MeterData::secretSMtoUCkey, and smart3p::MeterData::smGate.
timedHandleMessage()
void smart3p::UtilityCompany::timedHandleMessage (cMessage * msg) [protected], [virtual]
Default message handler.
Reimplemented from smart3p::Unit.
Definition at line 45 of file UtilityCompany.cc.
References UCAdapter::energyConsumptionProcessing(), smart3p::SMPacket::getCollGateID(), smart3p::SMPacket::getId(), smart3p::SMPacket::getSmGateID(), UCAdapter::registerSM(), UCAdapter::registerTTP(), UCAdapter::sessionKeyExchangeFromSM(), UCAdapter::sessionKeyExchangeFromTTP(), UCAdapter::sessionKeyStartFromTTP(), smart3p::SMPacket::setCollGateID(), smart3p::SMPacket::setId(), and smart3p::SMPacket::setSmGateID().
The documentation for this class was generated from the following files:
src/UtilityCompany.h
src/UtilityCompany.cc