smart3p::SMPacketDescriptor Class Reference
Public Member Functions
SMPacketDescriptor ()
virtual ~SMPacketDescriptor ()
virtual bool doesSupport (omnetpp::cObject *obj) const override
virtual const char ** getPropertyNames () const override
virtual const char * getProperty (const char *propertyname) const override
virtual int getFieldCount () const override
virtual const char * getFieldName (int field) const override
virtual int findField (const char *fieldName) const override
virtual unsigned int getFieldTypeFlags (int field) const override
virtual const char * getFieldTypeString (int field) const override
virtual const char ** getFieldPropertyNames (int field) const override
virtual const char * getFieldProperty (int field, const char *propertyname) const override
virtual int getFieldArraySize (void *object, int field) const override
virtual std::string getFieldValueAsString (void *object, int field, int i) const override
virtual bool setFieldValueAsString (void *object, int field, int i, const char *value) const override
virtual const char * getFieldStructName (int field) const override
virtual void * getFieldStructValuePointer (void *object, int field, int i) const override
Detailed Description
Definition at line 284 of file SMPacket_m.cc.
Constructor & Destructor Documentation
SMPacketDescriptor()
smart3p::SMPacketDescriptor::SMPacketDescriptor ()
Definition at line 313 of file SMPacket_m.cc.
 SMPacketDescriptor()
smart3p::SMPacketDescriptor::~SMPacketDescriptor () [virtual]
Definition at line 318 of file SMPacket_m.cc.
Member Function Documentation
doesSupport()
bool smart3p::SMPacketDescriptor::doesSupport (omnetpp::cObject * obj) const [override], [virtual]
Definition at line 323 of file SMPacket_m.cc.
findField()
int smart3p::SMPacketDescriptor::findField (const char * fieldName) const [override], [virtual]
Definition at line 389 of file SMPacket_m.cc.
getFieldArraySize()
int smart3p::SMPacketDescriptor::getFieldArraySize (void * object, int field) const [override], [virtual]
Definition at line 447 of file SMPacket_m.cc.
References getFieldCount().
getFieldCount()
int smart3p::SMPacketDescriptor::getFieldCount () const [override], [virtual]
Definition at line 345 of file SMPacket_m.cc.
getFieldName()
const char * smart3p::SMPacketDescriptor::getFieldName (int field) const [override], [virtual]
Definition at line 370 of file SMPacket_m.cc.
References getFieldCount().
getFieldProperty()
const char * smart3p::SMPacketDescriptor::getFieldProperty (int field, const char * propertyname) const [override], [virtual]
Definition at line 434 of file SMPacket_m.cc.
References getFieldCount().
getFieldPropertyNames()
const char ** smart3p::SMPacketDescriptor::getFieldPropertyNames (int field) const [override], [virtual]
Definition at line 421 of file SMPacket_m.cc.
References getFieldCount().
getFieldStructName()
const char * smart3p::SMPacketDescriptor::getFieldStructName (int field) const [override], [virtual]
Definition at line 501 of file SMPacket_m.cc.
References getFieldCount().
getFieldStructValuePointer()
void * smart3p::SMPacketDescriptor::getFieldStructValuePointer (void * object, int field, int i) const [override], [virtual]
Definition at line 514 of file SMPacket_m.cc.
References getFieldCount().
getFieldTypeFlags()
unsigned int smart3p::SMPacketDescriptor::getFieldTypeFlags (int field) const [override], [virtual]
Definition at line 351 of file SMPacket_m.cc.
References getFieldCount().
getFieldTypeString()
const char * smart3p::SMPacketDescriptor::getFieldTypeString (int field) const [override], [virtual]
Definition at line 402 of file SMPacket_m.cc.
References getFieldCount().
getFieldValueAsString()
std::string smart3p::SMPacketDescriptor::getFieldValueAsString (void * object, int field, int i) const [override], [virtual]
Definition at line 461 of file SMPacket_m.cc.
References smart3p::SMPacket::getCollGateID(), smart3p::SMPacket::getExtraInfo(), smart3p::SMPacket::getExtraInfoSize(), getFieldCount(), smart3p::SMPacket::getId(), smart3p::SMPacket::getSmGateID(), and smart3p::SMPacket::getValue().
getProperty()
const char * smart3p::SMPacketDescriptor::getProperty (const char * propertyname) const [override], [virtual]
Definition at line 339 of file SMPacket_m.cc.
getPropertyNames()
const char ** smart3p::SMPacketDescriptor::getPropertyNames () const [override], [virtual]
Definition at line 328 of file SMPacket_m.cc.
setFieldValueAsString()
bool smart3p::SMPacketDescriptor::setFieldValueAsString (void * object, int field, int i, const char * value) const [override], [virtual]
Definition at line 481 of file SMPacket_m.cc.
References getFieldCount(), smart3p::SMPacket::setCollGateID(), smart3p::SMPacket::setExtraInfo(), smart3p::SMPacket::setExtraInfoSize(), smart3p::SMPacket::setId(), smart3p::SMPacket::setSmGateID(), and smart3p::SMPacket::setValue().
The documentation for this class was generated from the following file:
src/SMPacket_m.cc