smart3p Namespace Reference
Data Structures
class Collector
Collector for smart3p::SmartMeter.
class DataGenerator
Generates data for smart3p::SmartMeter.
struct MeterData
Unused.
class SmartMeter
Simulation Smart Meter class.
class SMPacket
class SMPacketDescriptor
class TrustedThirdParty
Trusted Thrid Party for the simulation.
class Unit
Abstract class for the simulation.
class UtilityCompany
Utility Company class for the simulation.
Functions
Define_Module (Collector)
Define_Module (DataGenerator)
Define_Module (SmartMeter)
template<typename T , typename A >
std::ostream & operator<< (std::ostream &out, const std::vector< T, A > &vec)
template<typename T >
std::ostream & operator<< (std::ostream &out, const T &)
Register_Class (SMPacket)
Register_ClassDescriptor (SMPacketDescriptor)
void doParsimPacking (omnetpp::cCommBuffer *b, const SMPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SMPacket &obj)
Define_Module (TrustedThirdParty)
Define_Module (UtilityCompany)
Detailed Description
Namespace for the upper-level simulation classes.
Function Documentation
Define_Module() [1/5]
smart3p::Define_Module (Collector)
Define_Module() [2/5]
smart3p::Define_Module (UtilityCompany)
Define_Module() [3/5]
smart3p::Define_Module (DataGenerator)
Define_Module() [4/5]
smart3p::Define_Module (SmartMeter)
Define_Module() [5/5]
smart3p::Define_Module (TrustedThirdParty)
doParsimPacking()
void smart3p::doParsimPacking (omnetpp::cCommBuffer * b, const SMPacket & obj) [inline]
Definition at line 77 of file SMPacket_m.h.
References smart3p::SMPacket::parsimPack().
doParsimUnpacking()
void smart3p::doParsimUnpacking (omnetpp::cCommBuffer * b, SMPacket & obj) [inline]
Definition at line 78 of file SMPacket_m.h.
References smart3p::SMPacket::parsimUnpack().
operator<<() [1/2]
template<typename T , typename A >
std::ostream & smart3p::operator<< (std::ostream & out, const std::vector< T, A > & vec) [inline]
Definition at line 147 of file SMPacket_m.cc.
References Register_Class().
operator<<() [2/2]
template<typename T >
std::ostream& smart3p::operator<< (std::ostream & out, const T &) [inline]
Definition at line 143 of file SMPacket_m.cc.
Register_Class()
smart3p::Register_Class (SMPacket)
Register_ClassDescriptor()
smart3p::Register_ClassDescriptor (SMPacketDescriptor)