#location of the cryptopp headers
CRYPTO_INC_LOC = /usr/include/cryptopp
OUTPUT_PATH = ../../out/gcc-debug/src/cypto

CLASS_LIST = Requester.o SmartMeter.o TrustedParty.o UtilityCompany.o 
HEADER_LIST = -L SmartMeter.h -L UtilityCompany.h -L TrustedParty.h -L Requester.h -L examples.h

#package: clean build
#	ld -G $(CLASS_LIST) -fPIC -o libSmartMeter.so -lc

all:	clean build

#	g++ -Wall -g3 -std=c++11 -ggdb -O0 -I. -I$(CRYPTO_INC_LOC) $(HEADER_LIST) $(CLASS_LIST) list.h examples.cc -o examples.exe -lcryptopp -lpthread
#	g++ -Wall -g -std=c++11 -O2 -I./ -I$(CRYPTO_INC_LOC)  $(HEADER_LIST) $(CLASS_LIST) list.h examples.cc -o examples.exe -lcryptopp -lpthread

clean:
	rm -f *.o
	rm -f *.exe

build: $(CLASS_LIST)

%.o : %.cc
	g++ -Wall -c -g3 -std=c++11 -ggdb -O0 -I. -I$(CRYPTO_INC_LOC) $^ -o $@ -lcryptopp -lpthread
	g++ -Wall -c -g -std=c++11 -O2 -I./ -I$(CRYPTO_INC_LOC) $^ -o $@ -lcryptopp -lpthread

