//
// Generated file, do not edit! Created by nedtool 5.0 from MKPacket.msg.
//

#ifndef __SMART3P_MKPACKET_M_H
#define __SMART3P_MKPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace smart3p {

/**
 * Class generated from <tt>MKPacket.msg:6</tt> by nedtool.
 * <pre>
 * //
 * // Master Key Packet
 * //
 * packet MKPacket
 * {
 *     int id;
 *     double value;
 *     int smGateID;
 *     int collGateID;
 *     int pSize;
 *     string pBytes;
 *     int qSize;
 *     string qBytes;
 *     int gSize;
 *     string gBytes;
 *     int xSize;
 *     string xBytes;
 * }
 * </pre>
 */
class MKPacket : public ::omnetpp::cPacket
{
  protected:
    int id;
    double value;
    int smGateID;
    int collGateID;
    int pSize;
    ::omnetpp::opp_string pBytes;
    int qSize;
    ::omnetpp::opp_string qBytes;
    int gSize;
    ::omnetpp::opp_string gBytes;
    int xSize;
    ::omnetpp::opp_string xBytes;

  private:
    void copy(const MKPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MKPacket&);

  public:
    MKPacket(const char *name=nullptr, int kind=0);
    MKPacket(const MKPacket& other);
    virtual ~MKPacket();
    MKPacket& operator=(const MKPacket& other);
    virtual MKPacket *dup() const {return new MKPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual double getValue() const;
    virtual void setValue(double value);
    virtual int getSmGateID() const;
    virtual void setSmGateID(int smGateID);
    virtual int getCollGateID() const;
    virtual void setCollGateID(int collGateID);
    virtual int getPSize() const;
    virtual void setPSize(int pSize);
    virtual const char * getPBytes() const;
    virtual void setPBytes(const char * pBytes);
    virtual int getQSize() const;
    virtual void setQSize(int qSize);
    virtual const char * getQBytes() const;
    virtual void setQBytes(const char * qBytes);
    virtual int getGSize() const;
    virtual void setGSize(int gSize);
    virtual const char * getGBytes() const;
    virtual void setGBytes(const char * gBytes);
    virtual int getXSize() const;
    virtual void setXSize(int xSize);
    virtual const char * getXBytes() const;
    virtual void setXBytes(const char * xBytes);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MKPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MKPacket& obj) {obj.parsimUnpack(b);}

} // namespace smart3p

#endif // ifndef __SMART3P_MKPACKET_M_H

